### ISSUE TITLE
"Arities must be distinct" error when compiling jar in Clojure 1.8

### ISSUE THREAD

**Issue by camsaul** [plumatic/schema#339]
After switching to Clojure 1.8 I'm seeing an "Arities must be distinct" `RuntimeException` when running `lein uberjar`.

```bash
Caused by: java.lang.RuntimeException: Arities must be distinct
	at schema.core$make_fn_schema.invokeStatic(core.clj:1049)
	at metabase.driver.query_processor.expand$fn__20187.invokeStatic(expand.clj:101)
        ...
```

It's being triggered by a 2-arity `s/defn` function that looks like this: 

```clojure
(s/defn ^:ql ^:always-validate datetime-field :- FieldPlaceholder
  ([f _ unit] (datetime-field f unit))
  ([f unit]   (assoc (field f) :datetime-unit (normalize-token unit))))
```

This error never happened with Clojure 1.7. Am I doing something wrong?

**Comment by w01fe** [comment]
Thanks for the report.  I don't see why it shouldn't work.  I have no experience with direct linking and can't reproduce with this example, so if you could provide a test project that exhibits the error (or dig in further yourself) that would be a big help.  Thanks again!

**Comment by camsaul** [comment]
Hey @w01fe if you take a look at https://github.com/camsaul/metabase/blob/master/project.clj and run `lein uberjar` you'll get the error

**Comment by w01fe** [comment]
I looked into it and the issue seems to be that there are two copies of the
schema.core.One class floating around in this AOT compilation setting.

This causes the `(instance? One ...)` check in `arity-` to return false on
both arities (when it should return true on both), which causes the
assertion failure.

I've never used AOT myself so I'm not sure where to go from here, however.
