### ISSUE TITLE
Uberjar - java.lang.NoClassDefFoundError: schema/utils/PSimpleCell

### ISSUE THREAD

**Issue by sgrove** [plumatic/schema#354]
I get this error when running an uberjar that uses Schema (see below for the minimum repro case):

```
$lein clean && lein uberjar && java -jar target/uberjar/example-0.1.0-SNAPSHOT-standalone.jar
Loading dev environment...
Setting Schema to *always* validate every function:  false
Finished prepping dev environment.
Warning: environ value 3005 has been cast to string
PORT (env):
	 nil
Test fail:
Exception in thread "main" java.lang.NoClassDefFoundError: schema/utils/PSimpleCell
	at example.core$fn__11251$test_fail__11256.invoke(core.clj:66)
	at example.core$_main.invokeStatic(core.clj:77)
	at example.core$_main.doInvoke(core.clj:71)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at example.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: schema.utils.PSimpleCell
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

This happens whether `set-fn-validation!` is called with `true` or `false`:

```
(ns user
  (:require [schema.core :as s]))

(println "Loading dev environment...")

(def validate?
  false)
(println "Setting Schema to *always* validate every function: " validate?)
(s/set-fn-validation! validate?)

(println "Finished prepping dev environment.")
```

The dependencies look right, I don't see any conflicts around `schema` (and I use `:pedantic? :abort` in any case):
```
 [abengoa/clj-stripe "1.0.4" :exclusions [[org.clojure/data.json]]]
 [acyclic/squiggly-clojure "0.1.5"]
   [org.clojure/data.json "0.2.6"]
 [ch.qos.logback/logback-classic "1.1.3"]
   [ch.qos.logback/logback-core "1.1.3"]
   [org.slf4j/slf4j-api "1.7.7"]
 [cheshire "5.6.1"]
   [com.fasterxml.jackson.core/jackson-core "2.7.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.7.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.7.3"]
   [tigris "0.1.1"]
 [cider/cider-nrepl "0.12.0"]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clj-http "2.1.0"]
   [commons-codec "1.10" :exclusions [[org.clojure/clojure]]]
   [commons-io "2.4" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpclient "4.5.1" :exclusions [[org.clojure/clojure]]]
     [commons-logging "1.2"]
   [org.apache.httpcomponents/httpcore "4.4.4" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpmime "4.5.1" :exclusions [[org.clojure/clojure]]]
   [potemkin "0.4.3" :exclusions [[org.clojure/clojure]]]
     [clj-tuple "0.2.2"]
     [riddley "0.1.12"]
   [slingshot "0.12.2" :exclusions [[org.clojure/clojure]]]
 [clj-time "0.9.0"]
   [joda-time "2.6"]
 [clj-webdriver "0.7.2" :scope "test" :exclusions [[commons-codec]]]
   [org.mortbay.jetty/jetty "6.1.25" :scope "test"]
     [org.mortbay.jetty/jetty-util "6.1.25" :scope "test"]
     [org.mortbay.jetty/servlet-api "2.5-20081211" :scope "test"]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.stuartsierra/component "0.3.1"]
   [com.stuartsierra/dependency "0.2.0"]
 [compojure "1.5.0" :exclusions [[clj-time]]]
   [clout "2.1.2"]
   [medley "0.7.3"]
   [org.clojure/tools.macro "0.1.5"]
   [ring/ring-codec "1.0.0"]
   [ring/ring-core "1.4.0"]
     [commons-fileupload "1.3.1"]
     [org.clojure/tools.reader "0.9.1"]
 [crypto-password "0.2.0"]
   [com.lambdaworks/scrypt "1.4.0"]
   [crypto-equality "1.0.0"]
   [crypto-random "1.2.0"]
   [org.mindrot/jbcrypt "0.3m"]
 [environ "1.0.2"]
 [expectations "2.1.3" :exclusions [[org.clojure/clojure] [joda-time]]]
   [junit "4.12"]
     [org.hamcrest/hamcrest-core "1.3"]
   [org.clojure/clojurescript "0.0-3196"]
     [com.google.javascript/closure-compiler "v20150126"]
       [args4j "2.0.26"]
       [com.google.code.findbugs/jsr305 "1.3.9"]
       [com.google.code.gson/gson "2.2.4"]
       [com.google.guava/guava "18.0"]
       [com.google.javascript/closure-compiler-externs "v20150126"]
       [com.google.protobuf/protobuf-java "2.5.0"]
       [com.google.truth/truth "0.24"]
     [org.clojure/google-closure-library "0.0-20140718-946a7d39"]
       [org.clojure/google-closure-library-third-party "0.0-20140718-946a7d39"]
     [org.mozilla/rhino "1.7R5"]
 [hiccup "1.0.5"]
 [hickory "0.6.0"]
   [org.jsoup/jsoup "1.7.1"]
   [quoin "0.1.0"]
 [jonase/eastwood "0.2.3" :exclusions [[org.clojure/clojure]]]
   [org.clojars.brenton/google-diff-match-patch "0.1"]
   [org.ow2.asm/asm-all "4.2"]
 [jonase/kibit "0.1.2"]
   [org.clojure/core.logic "0.8.10"]
   [org.clojure/tools.cli "0.3.1"]
 [mvxcvi/clj-pgp "0.8.3" :exclusions [[org.clojure/tools.logging]]]
   [byte-streams "0.2.0"]
     [manifold "0.1.0"]
     [primitive-math "0.1.4"]
   [org.bouncycastle/bcpg-jdk15on "1.54"]
   [org.bouncycastle/bcprov-jdk15on "1.54"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/core.typed "0.3.22" :exclusions [[org.clojure/tools.reader]]]
   [org.clojure/core.cache "0.6.4"]
     [org.clojure/data.priority-map "0.0.4"]
   [org.clojure/core.contracts "0.0.4" :exclusions [[org.clojure/clojure]]]
     [org.clojure/core.unify "0.5.3"]
   [org.clojure/core.typed.rt "0.3.22"]
   [org.clojure/jvm.tools.analyzer "0.6.1" :exclusions [[org.clojure/clojurescript]]]
   [org.clojure/math.combinatorics "0.1.1" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.analyzer.jvm "0.6.8"]
     [org.clojure/core.memoize "0.5.7"]
     [org.clojure/tools.analyzer "0.6.7"]
   [org.clojure/tools.namespace "0.2.11"]
 [org.clojure/java.jdbc "0.5.8"]
 [org.clojure/tools.logging "0.3.1"]
 [org.clojure/tools.nrepl "0.2.12"]
 [org.postgresql/postgresql "9.4-1201-jdbc41"]
 [org.seleniumhq.selenium/selenium-htmlunit-driver "2.52.0" :scope "test" :exclusions [[org.eclipse.jetty/jetty-io] [com.google.guava/guava] [com.google.code.gson/gson] [commons-codec]]]
   [commons-collections "3.2.2" :scope "test"]
   [net.sourceforge.htmlunit/htmlunit "2.18" :scope "test" :exclusions [[commons-collections]]]
     [net.sourceforge.cssparser/cssparser "0.9.16" :scope "test"]
       [org.w3c.css/sac "1.3" :scope "test"]
     [net.sourceforge.htmlunit/htmlunit-core-js "2.17" :scope "test"]
     [net.sourceforge.nekohtml/nekohtml "1.9.22" :scope "test" :exclusions [[xerces/xercesImpl]]]
     [org.apache.commons/commons-lang3 "3.4" :scope "test"]
     [org.eclipse.jetty.websocket/websocket-client "9.2.12.v20150709" :scope "test"]
       [org.eclipse.jetty.websocket/websocket-common "9.2.12.v20150709" :scope "test"]
         [org.eclipse.jetty.websocket/websocket-api "9.2.12.v20150709" :scope "test"]
       [org.eclipse.jetty/jetty-util "9.2.12.v20150709"]
     [xalan "2.7.2" :scope "test" :exclusions [[xerces/xercesImpl]]]
       [xalan/serializer "2.7.2" :scope "test"]
     [xerces/xercesImpl "2.11.0" :scope "test"]
       [xml-apis "1.4.01" :scope "test"]
   [org.seleniumhq.selenium/selenium-support "2.52.0" :scope "test"]
     [org.seleniumhq.selenium/selenium-remote-driver "2.52.0" :scope "test"]
       [cglib/cglib-nodep "2.1_3" :scope "test"]
       [org.seleniumhq.selenium/selenium-api "2.52.0" :scope "test"]
 [org.seleniumhq.selenium/selenium-java "2.53.0" :scope "test" :exclusions [[org.seleniumhq.selenium/selenium-api] [org.eclipse.jetty/jetty-io] [com.google.guava/guava] [com.google.code.gson/gson] [org.seleniumhq.selenium/selenium-support] [commons-codec] [org.apache.httpcomponents/httpclient] [org.seleniumhq.selenium/selenium-remote-driver]]]
   [org.seleniumhq.selenium/selenium-chrome-driver "2.53.0" :scope "test"]
   [org.seleniumhq.selenium/selenium-edge-driver "2.53.0" :scope "test"]
     [org.apache.commons/commons-exec "1.3" :scope "test"]
   [org.seleniumhq.selenium/selenium-firefox-driver "2.53.0" :scope "test"]
   [org.seleniumhq.selenium/selenium-ie-driver "2.53.0" :scope "test"]
     [net.java.dev.jna/jna-platform "4.1.0" :scope "test"]
     [net.java.dev.jna/jna "4.1.0" :scope "test"]
   [org.seleniumhq.selenium/selenium-leg-rc "2.53.0" :scope "test"]
   [org.seleniumhq.selenium/selenium-safari-driver "2.53.0" :scope "test"]
     [io.netty/netty "3.5.7.Final" :scope "test"]
 [prismatic/schema-generators "0.1.0" :exclusions [[prismatic/schema]]]
   [org.clojure/test.check "0.9.0"]
 [prismatic/schema "1.1.0"]
 [refactor-nrepl "2.2.0"]
 [ring-logger "0.7.6"]
   [org.clojars.pjlegato/clansi "1.3.0"]
 [ring/ring-json "0.4.0"]
 [ring "1.4.0" :exclusions [[clj-time]]]
   [ring/ring-devel "1.4.0"]
     [clj-stacktrace "0.2.8"]
     [ns-tracker "0.3.0"]
       [org.clojure/java.classpath "0.2.2"]
   [ring/ring-jetty-adapter "1.4.0"]
     [org.eclipse.jetty/jetty-server "9.2.10.v20150310"]
       [javax.servlet/javax.servlet-api "3.1.0"]
       [org.eclipse.jetty/jetty-http "9.2.10.v20150310"]
       [org.eclipse.jetty/jetty-io "9.2.10.v20150310"]
   [ring/ring-servlet "1.4.0"]
 [yesql "0.5.2"]
   [instaparse "1.4.1" :exclusions [[org.clojure/clojure]]]
```

This is triggered with very simple code here:
```
(ns example.core
  (:gen-class)
  (:require [schema.core :as s]))

(s/defn test-fail
  []
  (println "See if this blows everything up...")
  true)

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "PORT (env): ")
  (println "\t" (System/getenv "HTTP_URL"))
  (println "Test fail: ")
  (println "\t" (test-fail)))
```

Finally, this happens whether `{:aot :all}` or `{:aot []}` is set in the `:uberjar` profile.

I'm pretty lost, but this is replicable across all of my OSX machines, and on the CircleCI linux servers. Please let me know if there's anything obvious I might be missing, I'm not sure where else to look.

**Comment by sgrove** [comment]
Sorry, I should have mentioned in the final code snippet above that the error is triggered any time a function defined using `s/defn` is called (whether anything is annotated or not).

**Comment by sgrove** [comment]
In a desperate, random attempt after looking at `utils.clj` (in that jar), and thinking that maybe the classes weren't getting compiled AoT correctly, I explicitly added `schema.utils` to the `:aot` key:

```
{:profiles {:uberjar {:aot [example.core
                             schema.utils]
                       :main example.core}}
```

And it seems like the problem goes away. Trying a few things to force `schema.utils` to be required at the top level during uberjar so that it's properly compiled AoT,

**Comment by w01fe** [comment]
Sorry for the trouble, and thanks for digging into this!  It's really odd, since `schema.core` requires `schema.utils` in a standard, straightforward way.  I wonder if it's possibly a quirk with `definterface` (which we're using to get maximal performance on the check).  

Given all the trouble that has come up with this particular class, the simplest thing might be to just make SimpleVCell a Java class in Clojure, and keep the existing implementation (or do whatever else is reasonable) for cljs.  Thoughts?

**Comment by shriphani** [comment]
@sgrove my problem was AOT related as well but I didn't conduct such a thorough post-mortem. Anywho if it helps:

Formerly broken setup:
  1. lib1 with a main ns that uses schema.
  2. Another project that depended on lib1 and also on schema. And I got #351.

Fixed setup:
  1. Removed the main ns from lib1 (I actually removed all the `:gen-class` bits as well).

And then it all worked fine.

**Comment by w01fe** [comment]
I tried going down the java class road, in case you want to test it out:

https://github.com/plumatic/schema/compare/javaize-simple-cell

Unfortunately, cljsbuild does not seem to include Java class files during compilation, which means this probably isn't an acceptable solution by itself.   If this helps with AOT, however, we could look into a workaround like generating a shim in Clojure when the class file gets left out.

**Comment by w01fe** [comment]
Quick update: because of the cljsbuild issue, I think the Java class is a dead end -- but I have another approach in mind, and will try to get something up for testing in the next day or two.

**Comment by w01fe** [comment]
Had a few spare minutes -- @sgrove when you get a chance, can you please test if 

` [prismatic/schema "1.1.1-SNAPSHOT"]` solves your issues? 

Diff is here in case you're interested: https://github.com/plumatic/schema/compare/atomize-simple-cell

Much appreciated!

**Comment by sgrove** [comment]
Will give this a try later today, thanks!

**Comment by w01fe** [comment]
You're welcome, thanks @sgrove!  I've gone ahead and cut a 1.1.1 release since this definitely fixed #355, hopefully that will knock down this one as well.

**Comment by w01fe** [comment]
Please reopen if this is still a problem with 1.1.1+.  Thanks!

**Comment by sgrove** [comment]
@w01fe Thank you a *ton* for this!

**Comment by w01fe** [comment]
No problem, thanks for your patience :)
